### ISSUE TITLE
167 Test Case for UT

### ISSUE THREAD

**Issue by PhamTuanDuongs** [sechmachine727/fms-frontend#234]
@PhamTuanDuongs 

- [x] `UserServiceImplTest` : 38TC 100% Branch Coverage
- [x] `ActionServiceImplTest` 3TC 
- [x] `ClassFeedbackServiceImplTest` 7TC 100%BC
- [x] `ClassTraineeServiceImplTest` 8TC 100%BC
- [x] `HolidayServiceImplTest` 11TC 100%BC
- [x] `IssueServiceImplTest` 20TC 100%BC
- [x] `SchedulePresetServiceImplTest` 17TC 100%BC
- [x] `TopicAssessmentServiceImplTest` 2 TC100%BC
- [x] DeliveryTypeService 1TC 100%BC 
- [x] DepartmentService 1TC 100%BC 
- [x] FormatTypeService 2TC 100%BC 
- [x] KeyProgramService 2TC 100%BC
- [x] RoleService 2TC 100%BC
- [x] ScopeService 2TC 100%BC
- [x] TraineeTypeService 11TC 
- [x] EmailService 5TC 100%BC (0 Branch but 24/26 LC)

**Comment by sechmachine727** [comment]
@PhamTuanDuongs more work to do

**Comment by sechmachine727** [comment]
`HolidayServiceImplTest` added

**Comment by sechmachine727** [comment]
@PhamTuanDuongs `IssueServiceImplTest` added
